const projectData = [
  {
    name: 'Spectian User',
    desc: 'This is an android application for our college students, so that they can access some sort of material from this application itself.',
    img: 'assets/img/projects/spectian.png',
    link: 'https://github.com/vishwasracharya/Spectian',
    tags: ['Android App', 'Java', 'XML', 'Firebase'],
  },
  {
    name: 'Spectian Admin',
    desc: "This Android application is the admin part of the application called spectian, This is basically where the administrator and faculties of the college will handle this app to upload assignments, notices, book PDF's and all.",
    img: 'assets/img/projects/spectian-admin.png',
    link: 'https://github.com/vishwasracharya/Spectian-Admin',
    tags: ['Android App', 'Java', 'XML', 'Firebase'],
  },
  {
    name: 'Video Converter',
    desc: 'This is a web app that helps you convert videos to mp3, mp4, and other formats. I built this tools as a part of my company project, and I made some changes and updations to the code, and added it to GitHub.',
    img: 'assets/img/projects/video-converter.ico',
    link: 'https://github.com/vishwasracharya/ffmpeg-with-nodejs',
    tags: ['FFMPEG', 'JavaScript', 'Node.Js', 'Express', 'EJS'],
  },
  {
    name: 'Email Permutator',
    desc: 'A web app which generates random emails based on given name and domain. ',
    img: 'assets/img/projects/email-permutator.png',
    link: 'https://vishwasracharya.github.io/email-permutator',
    tags: ['HTML5', 'CSS3', 'JavaScript'],
  },
  {
    name: 'Email Spam Checker',
    desc: 'This is a tool which checks the spam words from the message of your email, Go on the Live Website to checkout by yourself.',
    img: 'assets/img/projects/email-spam-checker.png',
    link: 'https://vishwasracharya.github.io/email-spam-checker',
    tags: ['HTML5', 'CSS3', 'JavaScript'],
  },
  {
    name: 'Command Line Tools',
    desc: 'This repository contains all the command line tools that I have created when learning how to create this type of tools',
    img: 'assets/img/projects/command-line-tools.png',
    link: 'https://github.com/vishwasracharya/command_line_tools',
    tags: ['Node.Js', 'JavaScript'],
  },
  {
    name: 'Circle Animation',
    desc: 'A Basic circle animation which was a task given to me in one of the interview.',
    img: 'assets/img/projects/circle-animation.png',
    link: 'https://vishwasracharya.github.io/Circle-Animation',
    tags: ['HTML5', 'CSS3', 'JavaScript'],
  },
  {
    name: 'SalesBlink.io',
    desc: 'This is my very recent project that I worked during my internship @futureblink. This is a web application that helps the sales team to manage their sales process. It is a CRM system that helps the sales team to manage their sales process.',
    img: 'assets/img/projects/salesblink-io.png',
    link: 'https://salesblink.io',
    tags: ['Website', 'NodeJS', 'Javascript', 'Express', 'MongoDB'],
  },
  {
    name: 'PlayStory.io',
    desc: "This one is the second project of @futureblink. It is a website that creates an interactive environment in creating and watching videos, like videos that let's you play around.",
    img: 'assets/img/projects/playstory-io.png',
    link: 'https://playstory.io',
    tags: ['Website', 'NodeJS', 'Javascript', 'Express', 'MongoDB'],
  },
  {
    name: 'InstaCopy.ai',
    desc: 'This one is also a sub project of futureblink, And my work on this was to develop this website with different theme given to me but with the same content and Page structure.',
    img: 'assets/img/projects/instacopy-ai.png',
    link: 'https://instacopy.ai/',
    tags: ['Website', 'NodeJS', 'Javascript', 'Express', 'MongoDB'],
  },
  {
    name: 'StackGrab.io',
    desc: 'This one is also a sub project of futureblink, And my work on this was to develop required web pages and coding of required features, It also Included integration with Stripe Payment Gateway.',
    img: 'assets/img/projects/stackgrab-io.png',
    link: 'https://stackgrab.io/',
    tags: ['Website', 'NodeJS', 'Javascript', 'Express', 'MongoDB', 'Firebase'],
  },
  {
    name: 'NMR Enterprise',
    desc: "My first ever internship in Tech and I mostly contributed in the front-end development of this web application. It is the company's website that represents the company and its products.",
    img: 'assets/img/projects/nmr-enterprise.png',
    link: 'https://www.nmrenterprise.com/about-us.php',
    tags: ['Website', 'pHp', 'HTML', 'CSS', 'Javascript', 'SQL'],
  },
  {
    name: 'Basic Chatbot',
    desc: 'This chatbot is created using HTML, CSS and JS. This chatbot works on hardcoded responses. Hence it says Basic Chatbot. It is a simple chatbot that can be used for any kind of conversation.',
    img: 'assets/img/projects/basic-chatbot.png',
    link: 'https://vishwasracharya.github.io/Basic-Chatbot',
    tags: ['Website', 'HTML', 'CSS', 'Javascript', 'Git', 'GitHub', 'JQuery'],
  },
  {
    name: 'E-Library',
    desc: "A Project which is created while learning of ASP.NET, It is not my own design I've copied the designed from the tutorial. It is a library management system which is used by the students of the college.",
    img: 'assets/img/projects/elibrary.png',
    link: 'https://github.com/vishwasracharya/E-Library',
    tags: ['ASP.NET', 'HTML', 'CSS', 'Javascript', 'C#', 'MS-SQL'],
  },
  {
    name: 'Notes App',
    desc: 'A Notes App using only basic technologies, includes: HTML5, CSS3, JavaScript. It is a simple notes app that can be used for any kind of notes.',
    img: 'assets/img/projects/notes-basic.png',
    link: 'https://vishwasracharya.github.io/Notes-Basic',
    tags: ['HTML', 'CSS', 'Javascript', 'Git', 'GitHub', 'State Management'],
  },
  {
    name: 'College Material',
    desc: "This website will hold all the material which was in Vishwas-BE-IT repo but with this help od this you'll get to watch/learn directly from the website with a better view. It is still in development, once it gets finished I'll let you know.",
    img: 'assets/img/projects/college-material.png',
    link: 'https://623c9cc24fc2f1009f08737b--zesty-biscuit-790f4f.netlify.app',
    tags: ['HTML', 'CSS', 'Vue', 'Javascript', 'Git', 'GitHub'],
  },
  {
    name: 'Drum Kit',
    desc: 'Another website project which has a Drum Kit, I made it during the learning process of JavaScript. It is a simple drum kit that can be used to play/learn about music instruments.',
    img: 'assets/img/projects/drum-kit.png',
    link: 'https://vishwasracharya.github.io/Drum-Kit',
    tags: ['HTML', 'CSS', 'Javascript', 'Git', 'GitHub'],
  },
  {
    name: 'Basic Calculator',
    desc: 'A small project which I made during the learning of Web Development. It is a basic calculator which can be used to perform basic operations.',
    img: 'assets/img/projects/basic-calculator.png',
    link: 'https://vishwasracharya.github.io/Basic-Calculator',
    tags: ['HTML', 'CSS', 'Javascript', 'Git', 'GitHub'],
  },
  {
    name: 'Dice Game',
    desc: 'Its just a website which has a Dice Game, I made it during the learning process of JavaScript. It is a simple dice game that can be used to play/learn about games.',
    img: 'assets/img/projects/dice-game.png',
    link: 'https://vishwasracharya.github.io/Dice-Game',
    tags: ['HTML', 'CSS', 'Javascript', 'Git', 'GitHub'],
  },
  {
    name: 'Contact React App',
    desc: 'A basic React App which has a contact form and shows the data. A Fundamental Web App to learn React.',
    img: 'assets/img/projects/contact-react-app.png',
    link: 'https://627ff2729c197515110cf454--comfy-sherbet-6752db.netlify.app/',
    tags: ['React.Js', 'Javascript', 'Git', 'Netlify'],
  },
  {
    name: 'Landing Page React App',
    desc: 'A basic React App which has a morden day landing page, which has some information about clients, projects and all. This one was a task given to me before the job interview.',
    img: 'assets/img/projects/landing-page-react.png',
    link: 'https://vishwasracharya.github.io/landing-page-react/',
    tags: ['React.Js', 'Javascript', 'Git', 'GitHub'],
  },
  {
    name: 'Phone Dialer',
    desc: 'A basic website project which has a Phone Dialer, I made it during the learning process of HTML, CSS & JavaScript.',
    img: 'assets/img/projects/phonedialer.png',
    link: 'https://vishwasracharya.github.io/phonedialer',
    tags: ['HTML', 'CSS', 'Javascript', 'Git', 'GitHub'],
  },
  {
    name: 'General Projects',
    desc: 'A mix of different projects. (Clock, loading animation, morph animation)',
    img: 'assets/img/projects/general-projects.png',
    link: 'https://github.com/vishwasracharya/General-Projects',
    tags: ['HTML', 'CSS', 'Javascript', 'Git', 'GitHub'],
  },
];

export default projectData;
